name: Deployment Bot
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up the environment
      run: npm install
    - name: Verifying linting
      run: npm run lint
    - name: Building
      run: npm run build
    - name: Running tests
      run: npm run unit-tests
    - name: Deploying version
      uses: danitseitlin/npm-package-deployer@master
      with:
        pkg_name: dmock-server
        npm_access_token: ${{secrets.NPM_AUTH_TOKEN}}
        github_access_token: ${{secrets.G_AUTH_TOKEN}}
