# This is a basic workflow to help you get started with Actions

name: DeployBot

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    # branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Configuration GIT name
      run: git config --global user.name ${{secrets.BOT_NAME}}
    - name: Configuration GIT email
      run: git config --global user.email ${{secrets.BOT_EMAIL}}
    - name: Authenticating with NPM
      run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      # run: npm login ---registry=https://registry.npmjs.com/:${{secrets.NPM_AUTH}}
      # run: npm config set registry=https://registry.npmjs.com/dmock-server/:_authToken=${{secrets.NPM_AUTH}}
    - name: Setting up the environment
      run: npm install
    - name: Running verifications
      run: npm run pre-deploy
    - name: Deploying version
      run: git checkout . && node deploy.js
