name: CI
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up the environment
      run: npm install
    - name: Verifying linting
      run: npm run lint
    - name: Building
      run: npm run build
    - name: Running tests
      run: npm run unit-tests